name: allways_delivery_partner
description: Dedicated ALLways Delivery Partner Android application.
publish_to: "none"
version: 1.0.2+3
environment:
  sdk: ">=3.6.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.15.2
  firebase_auth: ^5.6.2
  google_sign_in: ^7.1.1
  cloud_firestore: ^5.6.12
  cloud_functions: ^5.6.2
  firebase_messaging: ^15.2.10
  geolocator: ^14.0.2
  flutter_map: ^6.0.0
  latlong2: ^0.9.0
  shared_preferences: ^2.5.3
  package_info_plus: ^8.3.1
  http: ^1.5.0
  dio: ^5.9.0
  google_fonts: ^6.2.1
  url_launcher: ^6.3.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter:
  uses-material-design: true
